language: go
sudo: required
env:
  - DATABASE_URL=postgres://postgres@localhost
services:
  - postgresql
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
script: go vet ./... && go test -race -cover ./...
