language: go
go:
  - 1.3
env:
  - DATABASE_URL=postgres://postgres@localhost
addons:
  postgresql: "9.3"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
install:
  - go get github.com/tools/godep
  - go get code.google.com/p/go.tools/cmd/cover
script: /home/travis/gopath/bin/godep go test -cover ./...
